
all: cpu mem threads io

clean:
	rm -f cpu mem threads io

cpu: cpu.c
	gcc -o cpu cpu.c -Wall

mem: mem.c
	gcc -o mem mem.c -Wall

threads: threads.c
	gcc -o threads threads.c -Wall -pthread

io: io.c
	gcc -o io io.c -Wall

